#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Bing-OpenWrt-4415u

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_HAS_SUBTARGETS=y
          CONFIG_HAS_DEVICES=y
          CONFIG_TARGET_BOARD="x86"
          CONFIG_TARGET_SUBTARGET="64"
          CONFIG_TARGET_PROFILE="DEVICE_generic"
          CONFIG_TARGET_ARCH_PACKAGES="x86_64"
          CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe"
          CONFIG_CPU_TYPE=" "
          CONFIG_LINUX_5_4=y
          CONFIG_DEFAULT_ath10k-firmware-qca9888=y
          CONFIG_DEFAULT_ath10k-firmware-qca988x=y
          CONFIG_DEFAULT_ath10k-firmware-qca9984=y
          CONFIG_DEFAULT_autocore=y
          CONFIG_DEFAULT_automount=y
          CONFIG_DEFAULT_autosamba=y
          CONFIG_DEFAULT_base-files=y
          CONFIG_DEFAULT_block-mount=y
          CONFIG_DEFAULT_brcmfmac-firmware-43602a1-pcie=y
          CONFIG_DEFAULT_busybox=y
          CONFIG_DEFAULT_ca-certificates=y
          CONFIG_DEFAULT_coremark=y
          CONFIG_DEFAULT_ddns-scripts_aliyun=y
          CONFIG_DEFAULT_ddns-scripts_dnspod=y
          CONFIG_DEFAULT_default-settings=y
          CONFIG_DEFAULT_dnsmasq-full=y
          CONFIG_DEFAULT_dropbear=y
          CONFIG_DEFAULT_e2fsprogs=y
          CONFIG_DEFAULT_fdisk=y
          CONFIG_DEFAULT_firewall=y
          CONFIG_DEFAULT_fstools=y
          CONFIG_DEFAULT_htop=y
          CONFIG_DEFAULT_iptables=y
          CONFIG_DEFAULT_iwinfo=y
          CONFIG_DEFAULT_kmod-8139cp=y
          CONFIG_DEFAULT_kmod-8139too=y
          CONFIG_DEFAULT_kmod-ath10k=y
          CONFIG_DEFAULT_kmod-ath5k=y
          CONFIG_DEFAULT_kmod-ath9k=y
          CONFIG_DEFAULT_kmod-ath9k-htc=y
          CONFIG_DEFAULT_kmod-bnx2=y
          CONFIG_DEFAULT_kmod-drm-amdgpu=y
          CONFIG_DEFAULT_kmod-e1000=y
          CONFIG_DEFAULT_kmod-e1000e=y
          CONFIG_DEFAULT_kmod-forcedeth=y
          CONFIG_DEFAULT_kmod-fs-f2fs=y
          CONFIG_DEFAULT_kmod-i40e=y
          CONFIG_DEFAULT_kmod-i40evf=y
          CONFIG_DEFAULT_kmod-igb=y
          CONFIG_DEFAULT_kmod-igbvf=y
          CONFIG_DEFAULT_kmod-ipt-raw=y
          CONFIG_DEFAULT_kmod-ixgbe=y
          CONFIG_DEFAULT_kmod-mlx4-core=y
          CONFIG_DEFAULT_kmod-mlx5-core=y
          CONFIG_DEFAULT_kmod-mmc-spi=y
          CONFIG_DEFAULT_kmod-nf-nathelper=y
          CONFIG_DEFAULT_kmod-nf-nathelper-extra=y
          CONFIG_DEFAULT_kmod-pcnet32=y
          CONFIG_DEFAULT_kmod-r8125=y
          CONFIG_DEFAULT_kmod-r8168=y
          CONFIG_DEFAULT_kmod-rt2800-usb=y
          CONFIG_DEFAULT_kmod-sdhci=y
          CONFIG_DEFAULT_kmod-sound-hda-codec-hdmi=y
          CONFIG_DEFAULT_kmod-sound-hda-codec-realtek=y
          CONFIG_DEFAULT_kmod-sound-hda-codec-via=y
          CONFIG_DEFAULT_kmod-sound-hda-core=y
          CONFIG_DEFAULT_kmod-sound-hda-intel=y
          CONFIG_DEFAULT_kmod-sound-i8x0=y
          CONFIG_DEFAULT_kmod-sound-via82xx=y
          CONFIG_DEFAULT_kmod-tulip=y
          CONFIG_DEFAULT_kmod-usb-audio=y
          CONFIG_DEFAULT_kmod-usb-hid=y
          CONFIG_DEFAULT_kmod-usb-net=y
          CONFIG_DEFAULT_kmod-usb-net-asix=y
          CONFIG_DEFAULT_kmod-usb-net-asix-ax88179=y
          CONFIG_DEFAULT_kmod-usb-net-rtl8150=y
          CONFIG_DEFAULT_kmod-usb-net-rtl8152=y
          CONFIG_DEFAULT_kmod-vmxnet3=y
          CONFIG_DEFAULT_libc=y
          CONFIG_DEFAULT_libgcc=y
          CONFIG_DEFAULT_libustream-openssl=y
          CONFIG_DEFAULT_lm-sensors=y
          CONFIG_DEFAULT_logd=y
          CONFIG_DEFAULT_luci=y
          CONFIG_DEFAULT_luci-app-accesscontrol=y
          CONFIG_DEFAULT_luci-app-adbyby-plus=y
          CONFIG_DEFAULT_luci-app-arpbind=y
          CONFIG_DEFAULT_luci-app-autoreboot=y
          CONFIG_DEFAULT_luci-app-cpufreq=y
          CONFIG_DEFAULT_luci-app-ddns=y
          CONFIG_DEFAULT_luci-app-filetransfer=y
          CONFIG_DEFAULT_luci-app-ipsec-vpnd=y
          CONFIG_DEFAULT_luci-app-nlbwmon=y
          CONFIG_DEFAULT_luci-app-ramfree=y
          CONFIG_DEFAULT_luci-app-sfe=y
          CONFIG_DEFAULT_luci-app-ssr-plus=y
          CONFIG_DEFAULT_luci-app-unblockmusic=y
          CONFIG_DEFAULT_luci-app-upnp=y
          CONFIG_DEFAULT_luci-app-vlmcsd=y
          CONFIG_DEFAULT_luci-app-vsftpd=y
          CONFIG_DEFAULT_luci-app-webadmin=y
          CONFIG_DEFAULT_luci-app-wol=y
          CONFIG_DEFAULT_luci-app-xlnetacc=y
          CONFIG_DEFAULT_luci-app-zerotier=y
          CONFIG_DEFAULT_luci-proto-bonding=y
          CONFIG_DEFAULT_mkf2fs=y
          CONFIG_DEFAULT_mtd=y
          CONFIG_DEFAULT_netifd=y
          CONFIG_DEFAULT_opkg=y
          CONFIG_DEFAULT_partx-utils=y
          CONFIG_DEFAULT_ppp=y
          CONFIG_DEFAULT_ppp-mod-pppoe=y
          CONFIG_DEFAULT_uci=y
          CONFIG_DEFAULT_uclient-fetch=y
          CONFIG_DEFAULT_urandom-seed=y
          CONFIG_DEFAULT_urngd=y
          CONFIG_DEFAULT_wget=y
          CONFIG_DEFAULT_wpad=y
          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
